version: '3.2'
services:
  recipesdb:
    image: mongo:5.0.0
    container_name: recipes-database
    ports:
      - 27017:27017
    volumes:
      - ./mongo:/data/db
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./rabbitmq/data/:/var/lib/rabbitmq/
      - ./rabbitmq/log/:/var/log/rabbitmq
    networks:
      - rabbitmq_net
networks:
  rabbitmq_net:
    driver: bridge
